services:
  traefik:
    image: traefik:v2.11
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--certificatesResolvers.devresolver.acme.tlschallenge=true"
      - "--certificatesResolvers.devresolver.acme.email=test@example.com"
      - "--certificatesResolvers.devresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
      - "--serversTransport.insecureSkipVerify=true"  # wichtig für self-signed certs
      - "--providers.file.filename=/etc/traefik/dynamic.yaml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/certs:/certs"
      - "./traefik/dynamic.yaml:/etc/traefik/dynamic.yaml"
    networks:
      - web

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
    networks:
      - web

networks:
  web:
    external: false
